package com.midea.saximanager.model;

import java.io.Serializable;
import java.util.Date;

public class CsEnterprise implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_enterprise.id
     *
     * @mbggenerated Mon Jun 01 01:23:07 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_enterprise.cs_epid
     *
     * @mbggenerated Mon Jun 01 01:23:07 CST 2020
     */
    private String csEpid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_enterprise.cs_name
     *
     * @mbggenerated Mon Jun 01 01:23:07 CST 2020
     */
    private String csName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_enterprise.cs_conperson
     *
     * @mbggenerated Mon Jun 01 01:23:07 CST 2020
     */
    private String csConperson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_enterprise.cs_phone
     *
     * @mbggenerated Mon Jun 01 01:23:07 CST 2020
     */
    private String csPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_enterprise.cs_register_money
     *
     * @mbggenerated Mon Jun 01 01:23:07 CST 2020
     */
    private Double csRegisterMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_enterprise.cs_stime
     *
     * @mbggenerated Mon Jun 01 01:23:07 CST 2020
     */
    private Date csStime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_enterprise.cs_squre
     *
     * @mbggenerated Mon Jun 01 01:23:07 CST 2020
     */
    private Double csSqure;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_enterprise.cs_pnum
     *
     * @mbggenerated Mon Jun 01 01:23:07 CST 2020
     */
    private Integer csPnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_enterprise.cs_offer
     *
     * @mbggenerated Mon Jun 01 01:23:07 CST 2020
     */
    private Boolean csOffer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_enterprise.cs_address_detail
     *
     * @mbggenerated Mon Jun 01 01:23:07 CST 2020
     */
    private String csAddressDetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_enterprise.cs_pname
     *
     * @mbggenerated Mon Jun 01 01:23:07 CST 2020
     */
    private String csPname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_enterprise.cs_cname
     *
     * @mbggenerated Mon Jun 01 01:23:07 CST 2020
     */
    private String csCname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_enterprise.cs_carea
     *
     * @mbggenerated Mon Jun 01 01:23:07 CST 2020
     */
    private String csCarea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cs_enterprise
     *
     * @mbggenerated Mon Jun 01 01:23:07 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_enterprise.id
     *
     * @return the value of cs_enterprise.id
     *
     * @mbggenerated Mon Jun 01 01:23:07 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_enterprise.id
     *
     * @param id the value for cs_enterprise.id
     *
     * @mbggenerated Mon Jun 01 01:23:07 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_enterprise.cs_epid
     *
     * @return the value of cs_enterprise.cs_epid
     *
     * @mbggenerated Mon Jun 01 01:23:07 CST 2020
     */
    public String getCsEpid() {
        return csEpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_enterprise.cs_epid
     *
     * @param csEpid the value for cs_enterprise.cs_epid
     *
     * @mbggenerated Mon Jun 01 01:23:07 CST 2020
     */
    public void setCsEpid(String csEpid) {
        this.csEpid = csEpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_enterprise.cs_name
     *
     * @return the value of cs_enterprise.cs_name
     *
     * @mbggenerated Mon Jun 01 01:23:07 CST 2020
     */
    public String getCsName() {
        return csName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_enterprise.cs_name
     *
     * @param csName the value for cs_enterprise.cs_name
     *
     * @mbggenerated Mon Jun 01 01:23:07 CST 2020
     */
    public void setCsName(String csName) {
        this.csName = csName == null ? null : csName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_enterprise.cs_conperson
     *
     * @return the value of cs_enterprise.cs_conperson
     *
     * @mbggenerated Mon Jun 01 01:23:07 CST 2020
     */
    public String getCsConperson() {
        return csConperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_enterprise.cs_conperson
     *
     * @param csConperson the value for cs_enterprise.cs_conperson
     *
     * @mbggenerated Mon Jun 01 01:23:07 CST 2020
     */
    public void setCsConperson(String csConperson) {
        this.csConperson = csConperson == null ? null : csConperson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_enterprise.cs_phone
     *
     * @return the value of cs_enterprise.cs_phone
     *
     * @mbggenerated Mon Jun 01 01:23:07 CST 2020
     */
    public String getCsPhone() {
        return csPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_enterprise.cs_phone
     *
     * @param csPhone the value for cs_enterprise.cs_phone
     *
     * @mbggenerated Mon Jun 01 01:23:07 CST 2020
     */
    public void setCsPhone(String csPhone) {
        this.csPhone = csPhone == null ? null : csPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_enterprise.cs_register_money
     *
     * @return the value of cs_enterprise.cs_register_money
     *
     * @mbggenerated Mon Jun 01 01:23:07 CST 2020
     */
    public Double getCsRegisterMoney() {
        return csRegisterMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_enterprise.cs_register_money
     *
     * @param csRegisterMoney the value for cs_enterprise.cs_register_money
     *
     * @mbggenerated Mon Jun 01 01:23:07 CST 2020
     */
    public void setCsRegisterMoney(Double csRegisterMoney) {
        this.csRegisterMoney = csRegisterMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_enterprise.cs_stime
     *
     * @return the value of cs_enterprise.cs_stime
     *
     * @mbggenerated Mon Jun 01 01:23:07 CST 2020
     */
    public Date getCsStime() {
        return csStime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_enterprise.cs_stime
     *
     * @param csStime the value for cs_enterprise.cs_stime
     *
     * @mbggenerated Mon Jun 01 01:23:07 CST 2020
     */
    public void setCsStime(Date csStime) {
        this.csStime = csStime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_enterprise.cs_squre
     *
     * @return the value of cs_enterprise.cs_squre
     *
     * @mbggenerated Mon Jun 01 01:23:07 CST 2020
     */
    public Double getCsSqure() {
        return csSqure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_enterprise.cs_squre
     *
     * @param csSqure the value for cs_enterprise.cs_squre
     *
     * @mbggenerated Mon Jun 01 01:23:07 CST 2020
     */
    public void setCsSqure(Double csSqure) {
        this.csSqure = csSqure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_enterprise.cs_pnum
     *
     * @return the value of cs_enterprise.cs_pnum
     *
     * @mbggenerated Mon Jun 01 01:23:07 CST 2020
     */
    public Integer getCsPnum() {
        return csPnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_enterprise.cs_pnum
     *
     * @param csPnum the value for cs_enterprise.cs_pnum
     *
     * @mbggenerated Mon Jun 01 01:23:07 CST 2020
     */
    public void setCsPnum(Integer csPnum) {
        this.csPnum = csPnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_enterprise.cs_offer
     *
     * @return the value of cs_enterprise.cs_offer
     *
     * @mbggenerated Mon Jun 01 01:23:07 CST 2020
     */
    public Boolean getCsOffer() {
        return csOffer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_enterprise.cs_offer
     *
     * @param csOffer the value for cs_enterprise.cs_offer
     *
     * @mbggenerated Mon Jun 01 01:23:07 CST 2020
     */
    public void setCsOffer(Boolean csOffer) {
        this.csOffer = csOffer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_enterprise.cs_address_detail
     *
     * @return the value of cs_enterprise.cs_address_detail
     *
     * @mbggenerated Mon Jun 01 01:23:07 CST 2020
     */
    public String getCsAddressDetail() {
        return csAddressDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_enterprise.cs_address_detail
     *
     * @param csAddressDetail the value for cs_enterprise.cs_address_detail
     *
     * @mbggenerated Mon Jun 01 01:23:07 CST 2020
     */
    public void setCsAddressDetail(String csAddressDetail) {
        this.csAddressDetail = csAddressDetail == null ? null : csAddressDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_enterprise.cs_pname
     *
     * @return the value of cs_enterprise.cs_pname
     *
     * @mbggenerated Mon Jun 01 01:23:07 CST 2020
     */
    public String getCsPname() {
        return csPname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_enterprise.cs_pname
     *
     * @param csPname the value for cs_enterprise.cs_pname
     *
     * @mbggenerated Mon Jun 01 01:23:07 CST 2020
     */
    public void setCsPname(String csPname) {
        this.csPname = csPname == null ? null : csPname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_enterprise.cs_cname
     *
     * @return the value of cs_enterprise.cs_cname
     *
     * @mbggenerated Mon Jun 01 01:23:07 CST 2020
     */
    public String getCsCname() {
        return csCname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_enterprise.cs_cname
     *
     * @param csCname the value for cs_enterprise.cs_cname
     *
     * @mbggenerated Mon Jun 01 01:23:07 CST 2020
     */
    public void setCsCname(String csCname) {
        this.csCname = csCname == null ? null : csCname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_enterprise.cs_carea
     *
     * @return the value of cs_enterprise.cs_carea
     *
     * @mbggenerated Mon Jun 01 01:23:07 CST 2020
     */
    public String getCsCarea() {
        return csCarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_enterprise.cs_carea
     *
     * @param csCarea the value for cs_enterprise.cs_carea
     *
     * @mbggenerated Mon Jun 01 01:23:07 CST 2020
     */
    public void setCsCarea(String csCarea) {
        this.csCarea = csCarea == null ? null : csCarea.trim();
    }
}