package com.midea.saximanager.model;

import java.io.Serializable;

public class TbArea implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_area.area_id
     *
     * @mbggenerated Mon Jun 01 00:08:40 CST 2020
     */
    private Integer areaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_area.area_name
     *
     * @mbggenerated Mon Jun 01 00:08:40 CST 2020
     */
    private String areaName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_area.area_type
     *
     * @mbggenerated Mon Jun 01 00:08:40 CST 2020
     */
    private Boolean areaType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_area.parent_id
     *
     * @mbggenerated Mon Jun 01 00:08:40 CST 2020
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_area
     *
     * @mbggenerated Mon Jun 01 00:08:40 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_area.area_id
     *
     * @return the value of tb_area.area_id
     *
     * @mbggenerated Mon Jun 01 00:08:40 CST 2020
     */
    public Integer getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_area.area_id
     *
     * @param areaId the value for tb_area.area_id
     *
     * @mbggenerated Mon Jun 01 00:08:40 CST 2020
     */
    public void setAreaId(Integer areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_area.area_name
     *
     * @return the value of tb_area.area_name
     *
     * @mbggenerated Mon Jun 01 00:08:40 CST 2020
     */
    public String getAreaName() {
        return areaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_area.area_name
     *
     * @param areaName the value for tb_area.area_name
     *
     * @mbggenerated Mon Jun 01 00:08:40 CST 2020
     */
    public void setAreaName(String areaName) {
        this.areaName = areaName == null ? null : areaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_area.area_type
     *
     * @return the value of tb_area.area_type
     *
     * @mbggenerated Mon Jun 01 00:08:40 CST 2020
     */
    public Boolean getAreaType() {
        return areaType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_area.area_type
     *
     * @param areaType the value for tb_area.area_type
     *
     * @mbggenerated Mon Jun 01 00:08:40 CST 2020
     */
    public void setAreaType(Boolean areaType) {
        this.areaType = areaType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_area.parent_id
     *
     * @return the value of tb_area.parent_id
     *
     * @mbggenerated Mon Jun 01 00:08:40 CST 2020
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_area.parent_id
     *
     * @param parentId the value for tb_area.parent_id
     *
     * @mbggenerated Mon Jun 01 00:08:40 CST 2020
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }
}