package com.midea.saximanager.model;

import java.io.Serializable;

public class TDept implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dept.id
     *
     * @mbggenerated Mon Jun 01 16:48:02 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dept.code
     *
     * @mbggenerated Mon Jun 01 16:48:02 CST 2020
     */
    private Integer code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dept.name
     *
     * @mbggenerated Mon Jun 01 16:48:02 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dept.parantid
     *
     * @mbggenerated Mon Jun 01 16:48:02 CST 2020
     */
    private Integer parantid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_dept
     *
     * @mbggenerated Mon Jun 01 16:48:02 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dept.id
     *
     * @return the value of t_dept.id
     *
     * @mbggenerated Mon Jun 01 16:48:02 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dept.id
     *
     * @param id the value for t_dept.id
     *
     * @mbggenerated Mon Jun 01 16:48:02 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dept.code
     *
     * @return the value of t_dept.code
     *
     * @mbggenerated Mon Jun 01 16:48:02 CST 2020
     */
    public Integer getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dept.code
     *
     * @param code the value for t_dept.code
     *
     * @mbggenerated Mon Jun 01 16:48:02 CST 2020
     */
    public void setCode(Integer code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dept.name
     *
     * @return the value of t_dept.name
     *
     * @mbggenerated Mon Jun 01 16:48:02 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dept.name
     *
     * @param name the value for t_dept.name
     *
     * @mbggenerated Mon Jun 01 16:48:02 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dept.parantid
     *
     * @return the value of t_dept.parantid
     *
     * @mbggenerated Mon Jun 01 16:48:02 CST 2020
     */
    public Integer getParantid() {
        return parantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dept.parantid
     *
     * @param parantid the value for t_dept.parantid
     *
     * @mbggenerated Mon Jun 01 16:48:02 CST 2020
     */
    public void setParantid(Integer parantid) {
        this.parantid = parantid;
    }
}