package com.midea.saximanager.model;

import java.io.Serializable;

public class TPermission implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission.id
     *
     * @mbggenerated Mon Jun 01 16:48:02 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission.name
     *
     * @mbggenerated Mon Jun 01 16:48:02 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission.menuname
     *
     * @mbggenerated Mon Jun 01 16:48:02 CST 2020
     */
    private String menuname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission.permission
     *
     * @mbggenerated Mon Jun 01 16:48:02 CST 2020
     */
    private String permission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission.url
     *
     * @mbggenerated Mon Jun 01 16:48:02 CST 2020
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission.flag
     *
     * @mbggenerated Mon Jun 01 16:48:02 CST 2020
     */
    private Integer flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission.zindex
     *
     * @mbggenerated Mon Jun 01 16:48:02 CST 2020
     */
    private Integer zindex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission.parantid
     *
     * @mbggenerated Mon Jun 01 16:48:02 CST 2020
     */
    private Integer parantid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_permission
     *
     * @mbggenerated Mon Jun 01 16:48:02 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission.id
     *
     * @return the value of t_permission.id
     *
     * @mbggenerated Mon Jun 01 16:48:02 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission.id
     *
     * @param id the value for t_permission.id
     *
     * @mbggenerated Mon Jun 01 16:48:02 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission.name
     *
     * @return the value of t_permission.name
     *
     * @mbggenerated Mon Jun 01 16:48:02 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission.name
     *
     * @param name the value for t_permission.name
     *
     * @mbggenerated Mon Jun 01 16:48:02 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission.menuname
     *
     * @return the value of t_permission.menuname
     *
     * @mbggenerated Mon Jun 01 16:48:02 CST 2020
     */
    public String getMenuname() {
        return menuname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission.menuname
     *
     * @param menuname the value for t_permission.menuname
     *
     * @mbggenerated Mon Jun 01 16:48:02 CST 2020
     */
    public void setMenuname(String menuname) {
        this.menuname = menuname == null ? null : menuname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission.permission
     *
     * @return the value of t_permission.permission
     *
     * @mbggenerated Mon Jun 01 16:48:02 CST 2020
     */
    public String getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission.permission
     *
     * @param permission the value for t_permission.permission
     *
     * @mbggenerated Mon Jun 01 16:48:02 CST 2020
     */
    public void setPermission(String permission) {
        this.permission = permission == null ? null : permission.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission.url
     *
     * @return the value of t_permission.url
     *
     * @mbggenerated Mon Jun 01 16:48:02 CST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission.url
     *
     * @param url the value for t_permission.url
     *
     * @mbggenerated Mon Jun 01 16:48:02 CST 2020
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission.flag
     *
     * @return the value of t_permission.flag
     *
     * @mbggenerated Mon Jun 01 16:48:02 CST 2020
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission.flag
     *
     * @param flag the value for t_permission.flag
     *
     * @mbggenerated Mon Jun 01 16:48:02 CST 2020
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission.zindex
     *
     * @return the value of t_permission.zindex
     *
     * @mbggenerated Mon Jun 01 16:48:02 CST 2020
     */
    public Integer getZindex() {
        return zindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission.zindex
     *
     * @param zindex the value for t_permission.zindex
     *
     * @mbggenerated Mon Jun 01 16:48:02 CST 2020
     */
    public void setZindex(Integer zindex) {
        this.zindex = zindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission.parantid
     *
     * @return the value of t_permission.parantid
     *
     * @mbggenerated Mon Jun 01 16:48:02 CST 2020
     */
    public Integer getParantid() {
        return parantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission.parantid
     *
     * @param parantid the value for t_permission.parantid
     *
     * @mbggenerated Mon Jun 01 16:48:02 CST 2020
     */
    public void setParantid(Integer parantid) {
        this.parantid = parantid;
    }
}